name:                AnnealedVRP
version:             0.1.0.0
github:              "LuisChDev/AnnealedVRP"
license:             BSD3
author:              "Luis Ch."
maintainer:          "luischa123@gmail.com"
copyright:           "2019 Luis Ch."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            TMS JSON backend
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LuisChdev/AnnealedVRP#readme>

dependencies:
- aeson >= 1.4
- base >= 4.7 && < 5
- containers >= 0.6
- esqueleto
- matrix
- monad-control >= 1.0
- monad-logger >= 0.3 
- mtl >= 2.2
- persistent
- persistent-postgresql
- persistent-template
- random
- resource-pool >= 0.2
- servant
- servant-server
- text >= 1.2
- time >= 1.8
- transformers >= 0.5
- unliftio-core >= 0.1
- vector >= 0.12
- wai >= 3.2
- warp >= 3.2

library:
  source-dirs: src

executables:
  AnnealedVRP-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AnnealedVRP

tests:
  AnnealedVRP-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AnnealedVRP
    - hspec >= 2.6
